### PR TITLE
Propose an API endpoint for statuspage

### PR DESCRIPTION
**Pull request by Andre601**
I was thinking of making an RFC to propose this, so here I am.

Essentially am I requesting feedback regarding the idea of an API endpoint for the Status page as so many out there do have one themself and upptime could benefit from that too.

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
This is a very very good idea!

**Comment by AnandChowdhary** [comment]
Once we decide to work on this, would you be interested in making the PR in upptime/status-page to generate the API endpoints as static files? :)

**Comment by Andre601** [comment]
I don't have the knowledge for this unfortunately.

**Comment by AnandChowdhary** [comment]
Noted, thanks for the RFC!

**Pull request merged**
